using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlashWing.HIME.Model.Common.Protocol;

namespace FlashWing.HIME.Script.Model.Common.Protocol
{

    [ProtoInclude(1, typeof(ProtoPlayer))]
    [ProtoInclude(2, typeof(ProtoGirl))]
    [ProtoInclude(3, typeof(ProtoWidget))]
    [ProtoInclude(4, typeof(ProtoWidgetGroup))]
    [ProtoInclude(5, typeof(ProtoBattleGroup))]
    [ProtoInclude(8, typeof(ProtoItem))]
    [ProtoInclude(10, typeof(ProtoStage))]
    [ProtoInclude(11, typeof(ProtoMail))]
    [ProtoInclude(12, typeof(ProtoPlayerInfo))]
    [ProtoInclude(13, typeof(ProtoRecruit))]
    [ProtoInclude(14, typeof(ProtoNotice))]
    [ProtoInclude(15, typeof(ProtoAchievement))]
    [ProtoInclude(17, typeof(ProtoArea))]
    [ProtoInclude(18, typeof(ProtoShopItem))]
    [ProtoInclude(19, typeof(ProtoActivity))]
    [ProtoInclude(21, typeof(ProtoExpeditionMission))]
    [ProtoInclude(22, typeof(ProtoWeeklyMission))]
    [ProtoInclude(23, typeof(ProtoAreaDailyMission))]
    [ProtoInclude(24, typeof(ProtoActivityDailyMission))]
    [ProtoInclude(25, typeof(ProtoCharge))]
    [ProtoInclude(26, typeof(ProtoBattleDrop))]
    [ProtoInclude(27, typeof(ProtoCollect))]
    [ProtoInclude(28, typeof(ProtoViewItem))]
    [ProtoInclude(29, typeof(ProtoActivityAchievement))]
    [ProtoInclude(30, typeof(ProtoActivityMission))]
    [ProtoInclude(31, typeof(ProtoActivityDailyMission))]
    [ProtoInclude(32, typeof(RewardPool))]
    [ProtoInclude(33, typeof(ProtoRanking))]
    [ProtoInclude(34, typeof(ProtoPang))]
    [ProtoInclude(35, typeof(ProtoAreaMission))]
    [ProtoInclude(36, typeof(ProtoBuild))]
    [ProtoInclude(37, typeof(ProtoRoleBattleGroup))]
    [ProtoInclude(38, typeof(ProtoSevenLogin))]
    [ProtoInclude(39, typeof(ProtoTodayTotalInfo))]
    [ProtoInclude(40, typeof(ProtoNightmareStage))]
    [ProtoInclude(41, typeof(ProtoRookieTask))]
    [ProtoInclude(42, typeof(ProtoCG))]
    [ProtoInclude(43, typeof(ProtoEffectiveTenRecruitTime))]
    [ProtoInclude(44, typeof(ProtoTenRecruit))]
    [ProtoInclude(45, typeof(ProtoTenRecruitConfig))]
    [ProtoInclude(46, typeof(ProtoShopItemLikeInfo))]
    [ProtoInclude(47, typeof(ProtoGacya))]
    [ProtoInclude(48, typeof(ProtoBikiniStage))]
    [ProtoInclude(49, typeof(ProtoBikiniStageMission))]
    [ProtoInclude(50, typeof(ProtoBeachVolleyball))]
    [ProtoInclude(51, typeof(ProtoWidgetExchange))]
    [ProtoInclude(52, typeof(ProtoBikiniTask))]
    [ProtoInclude(53, typeof(ProtoBikiniBackground))]
    [ProtoInclude(54, typeof(ProtoWeeklyStage))]
    [ProtoInclude(55, typeof(ProtoWeeklyShop))]
    [ProtoInclude(56, typeof(ProtoSuitDevelop))]
    [ProtoInclude(57, typeof(ProtoMCVBase))]
    [ProtoInclude(58, typeof(ProtoMCVRoom))]
    [ProtoInclude(59, typeof(ProtoGirlBubble))]
    [ProtoInclude(60, typeof(ProtoMCVPreTaskActivity))]
    [ProtoInclude(61, typeof(ProtoTechTree))]
    [ProtoInclude(62, typeof(ProtoGhostMission))]
    [ProtoInclude(63, typeof(ProtoSignInMonth))]
    [ProtoInclude(64, typeof(ProtoCriticalPointStage))]
    [ProtoInclude(65, typeof(ProtoChristmas))]
    [ProtoInclude(66, typeof(ProtoChristmasMission))]
    [ProtoInclude(67, typeof(CriticalPointRewardPoolCell))]
    [ProtoInclude(68, typeof(ProtoCriticalPointMission))]
    [ProtoInclude(69, typeof(ProtoCriticalPointAchievement))]
    [ProtoInclude(70, typeof(ProtoCriticalPointJackpot))]
    [ProtoInclude(71, typeof(DailyStageCount))]
    [ProtoInclude(72, typeof(ProtoTower))]
    [ProtoInclude(73, typeof(ProtoTowerStage))]
    [ProtoInclude(74, typeof(ProtoTowerBossProperty))]
    [ProtoInclude(75, typeof(ProtoFriend))]
    [ProtoInclude(76, typeof(ProtoATPlayer))]
    [ProtoInclude(77, typeof(ProtoATBossInfo))]
    [ProtoInclude(78, typeof(ProtoATAssistRecord))]
    [ProtoInclude(79, typeof(ProtoFriendInfo))]
    [ProtoInclude(80, typeof(ProtoATRecordForView))]
    [ProtoInclude(81, typeof(ATBossView))]
    [ProtoInclude(82, typeof(ProtoFriendGirlInfo))]
    [ProtoInclude(83, typeof(ProtoATBossRankView))]
    [ProtoInclude(84, typeof(ATBossRankAwardView))]
    [ProtoInclude(85, typeof(ProtoFriendData))]
    [ProtoInclude(86, typeof(ProtoQuickCollectMCV))]
    [ProtoInclude(87, typeof(ProtoQuickCollectBubble))]
    [ProtoInclude(88, typeof(ProtoSeriesLogin))]
    [ProtoInclude(89, typeof(ProtoTalentTower))]
    [ProtoInclude(90, typeof(ProtoTalentPlayer))]
    [ProtoInclude(91, typeof(ProtoBattleMonsterStatus))]
    [ProtoInclude(92, typeof(ProtoTask))]
    [ProtoInclude(93, typeof(ProtoEVAChapter))]
    [ProtoInclude(94, typeof(ProtoEVADiffDesc))]
    [ProtoInclude(95, typeof(ProtoEVATechRoom))]
    [ProtoInclude(96, typeof(ProtoEVAOrder))]
    [ProtoInclude(97, typeof(ProtoEVAGirl))]
    [ProtoInclude(98, typeof(ProtoEVABase))]
    [ProtoInclude(99, typeof(ProtoEVAAreaRepairInfo))]
    [ProtoInclude(101, typeof(ProtoDailyFlag))]
    [ProtoInclude(102, typeof(ProtoHistoryView))]
    [ProtoInclude(103, typeof(ProtoAccumulateLogin))]
    [ProtoInclude(104, typeof(ProtoAchiRankLvl))]
    [ProtoInclude(105, typeof(ProtoMiniMission))]
    [ProtoInclude(106, typeof(ProtoEveOfNationalWarPVE))]
    [ProtoInclude(107, typeof(ProtoEveOfNationalWarPVP))]
    [ProtoInclude(108, typeof(ProtoHonor))]
    [ProtoInclude(109, typeof(ProtoPlayerMirror))]
    [ProtoInclude(110, typeof(ProtoGirlMirror))]
    [ProtoInclude(111, typeof(ProtoHonorBase))]
    [ProtoInclude(112, typeof(ProtoStoryStage))]
    [ProtoInclude(113, typeof(ProtoSweetActivity))]
    [ProtoInclude(114, typeof(ProtoSeasonFighter))]
    [ProtoInclude(115, typeof(ProtoSeasonFightLog))]
    [ProtoInclude(116, typeof(ProtoBattleDesc))]
    [ProtoInclude(117, typeof(ProtoFighterDesc))]
    [ProtoInclude(119, typeof(ProtoSeasonBattleGroup))]
    [ProtoInclude(120, typeof(ProtoSpecialRanking))]
    [ProtoInclude(121, typeof(ProtoNationalWar))]
    [ProtoInclude(122, typeof(ProtoNationalWarHexStatus))]
    [ProtoInclude(123, typeof(ProtoNationalWarCampInfo))]
    [ProtoInclude(124, typeof(ProtoNationalWarFightLog))]
    [ProtoInclude(125, typeof(ProtoBikiniBoss))]
    [ProtoInclude(126, typeof(ProtoBikiniBBQ))]
    [ProtoInclude(127, typeof(ProtoBikiniSeaFloor))]
    [ProtoInclude(128, typeof(ProtoBigEvent))]
    [ProtoInclude(129, typeof(ProtoSakuraWars))]
    [ProtoInclude(131, typeof(ProtoActivityConfig))]
    [ProtoInclude(132, typeof(ProtoGirlSkinConfig))]
    [ProtoInclude(133, typeof(ProtoURAwakeConfig))]
    [ProtoInclude(134, typeof(ProtoRiceCake))]
    [ProtoInclude(135, typeof(ProtoNewYearBoss))]
    [ProtoInclude(136, typeof(ProtoTexun))]
    [ProtoInclude(137, typeof(ProtoBeforeDawn))]
    [ProtoInclude(138, typeof(ProtoStageDropView))]
    [ProtoInclude(139, typeof(ProtoStarship))]
    [ProtoInclude(140, typeof(ProtoStarshipWeapon))]
    [ProtoInclude(141, typeof(ProtoStarshipWeaponFavor))]
    [ProtoInclude(142, typeof(ProtoStarshipBase))]
    [ProtoInclude(143, typeof(ProtoStarshipFetter))]
    [ProtoInclude(144, typeof(ProtoStarshipExplore))]
    [ProtoInclude(145, typeof(ProtoBattleReport))]
    [ProtoInclude(146, typeof(ProtoStarTowerStage))]
    [ProtoContract]
    [Serializable]
    public class ProtoBase
    {
        [ProtoMember(100)]
        public long UserId;
        //[ProtoMember(1)]
        //public byte[] ProtoData;
        [ProtoIgnore]
        public bool IsNew;
        protected ProtoBase()
        {
            this.IsNew = true;
        }
    }
}
