using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlashWing.HIME.Model.Common.Enum
{
    public enum ActivityType
    {
        无,
        克尔贝洛,
        泳装活动1,
        泳装活动2,
        泳装活动3,
        泳装活动4,
        B站联动,
        一体机改造,
        基地车前置,
        基地车正式版,
        万圣狂欢,
        临界点,
        圣诞活动,
        春节活动1,
        春节活动2,
        春节活动3,
        春节活动4,
        月面的大暴走,
        EVA活动总,
        EVA活动一期,
        EVA活动二期,
        等不到的黎明,
        黑色方舟计划,
        昨日头条,
        给糖也捣蛋,
        称号任务,
        EVA2活动总,
        EVA2活动一期,
        EVA2活动二期,
        情人节japan2021,
        轩辕剑联动,
        特殊活动1,
        特殊活动2,
        特殊活动3,
        特殊活动4,
        攻壳机动队,
        樱花大战,
        暴风雨之夜,
        元旦活动2022,
        彼方之风,
        空镜,
        怪诞艺术家,
        小心陷阱,
        幻想朋友,
        勇士,
        莎伦的一天,
        春节活动2023,
        红线,
        占位8,
        占位9,
        占位10,
        占位11,
        占位12,
        占位13,
        占位14,
        占位15,
        占位16,
        占位17,
        占位18,
        占位19,
        占位20
    }
}
