using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlashWing.HIME.Model.Common.Enum
{
    public enum SceneType
    {
        无,
        剧情任务,
        解锁任务,
        普通赏金,
        简单赏金,
        困难赏金,
        紧急赏金,
        晋级任务,
        日常任务,
        角色列传,
        引导任务,
        克尔贝洛之影,
        区域解锁任务,
        测试关卡,
        个人副本,
        夏日回忆,
        周常副本,
        B站联动,
        基地车前置任务,
        临界点,
        曜日副本,
        春节2019,
        能力测验,
        天赋爬塔,
        月面的大暴走,
        EVA限时BOSS,
        EVA关卡,
        等不到的黎明,
        给糖也捣蛋,
        国战前夕PVE,
        国战前夕PVP,
        国战前夕剧情,
        情人节japan2021,
        竞技场PVP,
        国战小怪,
        国战BOSS,
        国战PVP,
        轩辕剑联动,
        泳装活动关卡,
        海底两万里,
        攻壳联动,
        樱花联动小怪,
        樱花联动BOSS,
        暴风雨之夜,
        元旦2022小怪,
        元旦2022BOSS,
        元旦活动BOSS,
        特训BOSS,
        彼方之风小怪,
        彼方之风BOSS,
        彼方之风小游戏,
        空镜,
        怪诞艺术家小怪,
        怪诞艺术家BOSS,
        小心陷阱,
        幻想朋友,
        勇士,
        木桩测试,
        莎伦的一天,
        基地车爬塔关,
        春节2023小怪,
        春节2023BOSS,
        红线,
        占位12,
        占位13,
        占位14,
        占位15,
        占位16,
        占位17,
        占位18,
        占位19,
        占位20
    }
}
